# Generated by Django 5.1.7 on 2025-05-26 00:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherBanks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Other Bank',
                'verbose_name_plural': 'Other Banks',
            },
        ),
        migrations.CreateModel(
            name='OtherBankAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=255)),
                ('balance', models.TextField()),
                ('user', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='other_banks.otherbanks')),
            ],
            options={
                'verbose_name': 'Other Bank Account',
                'verbose_name_plural': 'Other Bank Accounts',
            },
        ),
    ]
