# Generated by Django 5.1.7 on 2025-05-16 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transaction', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_account_number', models.CharField(max_length=30)),
                ('sender_bank', models.CharField(max_length=255)),
                ('receiver_account_number', models.CharField(max_length=30)),
                ('receiver_bank', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('frequency', models.PositiveSmallIntegerField()),
                ('start_date', models.DateTimeField()),
                ('duration', models.PositiveSmallIntegerField()),
                ('next_payment_date', models.DateTimeField()),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], max_length=15)),
                ('transaction_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='transaction.transactiontypes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Scheduled Payment',
                'verbose_name_plural': 'Scheduled Payments',
            },
        ),
    ]
