# Generated by Django 5.1.7 on 2025-05-25 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionFees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Transaction Fee',
                'verbose_name_plural': 'Transaction Fees',
            },
        ),
        migrations.CreateModel(
            name='TransactionTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Transaction Type',
                'verbose_name_plural': 'Transaction Types',
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(max_length=32, unique=True)),
                ('datetime', models.TextField()),
                ('amount', models.TextField()),
                ('sender_account_number', models.TextField()),
                ('sender_bank', models.CharField(max_length=255)),
                ('receiver_account_number', models.TextField()),
                ('receiver_bank', models.CharField(max_length=255)),
                ('note', models.TextField(blank=True)),
                ('transaction_fees_applied', models.BooleanField()),
                ('receiver', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='receiver_transactions_set', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='sender_transactions_set', to=settings.AUTH_USER_MODEL)),
                ('transaction_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='transaction.transactiontypes')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
        migrations.CreateModel(
            name='TransactionFeesInTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_reference_id', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transaction.transactions')),
            ],
            options={
                'verbose_name': 'Transaction Fees in Transaction',
                'verbose_name_plural': 'Transaction Fees in Transactions',
            },
        ),
        migrations.CreateModel(
            name='UserTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('send', 'Send'), ('receive', 'Receive')], max_length=20)),
                ('resulting_balance', models.TextField()),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.transactions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Transaction',
                'verbose_name_plural': 'User Transactions',
            },
        ),
    ]
