# Generated by Django 5.1.7 on 2025-04-18 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transaction", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactions",
            name="note",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
