# Generated by Django 5.1.7 on 2025-04-06 09:26

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCardDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('strativa_card_number', models.CharField(max_length=19)),
                ('strativa_card_created', models.DateField(default=django.utils.timezone.now)),
                ('strativa_card_expiry', models.DateField(default=datetime.datetime(2028, 4, 6, 9, 26, 7, 978250, tzinfo=datetime.timezone.utc))),
                ('strativa_card_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('strativa_card_cvv', models.IntegerField()),
                ('is_online_card_active', models.BooleanField(default=False)),
                ('online_card_number', models.CharField(blank=True, max_length=19, null=True)),
                ('online_card_created', models.DateField(blank=True, null=True)),
                ('online_card_expiry', models.DateField(blank=True, null=True)),
                ('online_card_cvv', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Card Detail',
                'verbose_name_plural': 'User Card Details',
            },
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Data',
                'verbose_name_plural': 'User Data',
            },
        ),
    ]
