# Generated by Django 5.1.7 on 2025-04-10 13:09

import django.db.models.deletion
import my_accounts.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserCardDetails",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("strativa_card_number", models.CharField(max_length=16, unique=True)),
                ("strativa_card_created", models.DateTimeField()),
                ("strativa_card_expiry", models.DateTimeField()),
                ("strativa_card_cvv", models.CharField(max_length=3)),
                ("is_online_card_active", models.BooleanField(default=False)),
                (
                    "online_card_number",
                    models.CharField(blank=True, max_length=19, null=True, unique=True),
                ),
                ("online_card_created", models.DateTimeField(blank=True, null=True)),
                ("online_card_expiry", models.DateTimeField(blank=True, null=True)),
                (
                    "online_card_cvv",
                    models.CharField(blank=True, max_length=3, null=True),
                ),
            ],
            options={
                "verbose_name": "User Card Detail",
                "verbose_name_plural": "User Card Details",
            },
        ),
        migrations.CreateModel(
            name="UserData",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("middle_name", models.CharField(blank=True, max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                (
                    "profile_picture",
                    models.ImageField(
                        default="images/logo.png",
                        upload_to=my_accounts.models.UserData.save_profile_picture_to,
                    ),
                ),
                (
                    "user_card_details",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_accounts.usercarddetails",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Data",
                "verbose_name_plural": "User Data",
            },
        ),
    ]
