# Generated by Django 5.1.7 on 2025-05-25 17:11

import django.db.models.deletion
import my_accounts.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('transaction', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Account Type',
                'verbose_name_plural': 'Account Types',
            },
        ),
        migrations.CreateModel(
            name='StrativaBanks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Strativa Bank',
                'verbose_name_plural': 'Strativa Banks',
            },
        ),
        migrations.CreateModel(
            name='UserCardDetails',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('strativa_card_number', models.TextField()),
                ('strativa_card_created', models.TextField()),
                ('strativa_card_expiry', models.TextField()),
                ('strativa_card_cvv', models.TextField()),
                ('is_online_card_active', models.TextField()),
                ('online_card_number', models.TextField(blank=True, null=True)),
                ('online_card_created', models.TextField(blank=True, null=True)),
                ('online_card_expiry', models.TextField(blank=True, null=True)),
                ('online_card_cvv', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'User Card Detail',
                'verbose_name_plural': 'User Card Details',
            },
        ),
        migrations.CreateModel(
            name='UserAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashed_account_number', models.TextField(blank=True)),
                ('account_number', models.TextField(blank=True, unique=True)),
                ('balance', models.TextField(blank=True)),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_accounts.accounttypes')),
                ('bank', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='my_accounts.strativabanks')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Account',
                'verbose_name_plural': 'User Accounts',
            },
        ),
        migrations.CreateModel(
            name='UserTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(max_length=255, unique=True)),
                ('transaction_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='transaction.transactiontypes')),
            ],
            options={
                'verbose_name': 'User Type',
                'verbose_name_plural': 'User Types',
            },
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=765)),
                ('profile_picture', models.ImageField(default='images/logo.png', upload_to=my_accounts.models.UserData.save_profile_picture_to)),
                ('email', models.EmailField(max_length=255)),
                ('user_card_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_accounts.usercarddetails')),
                ('user_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='my_accounts.usertypes')),
            ],
            options={
                'verbose_name': 'User Data',
                'verbose_name_plural': 'User Data',
            },
        ),
    ]
