# Generated by Django 5.1.7 on 2025-04-07 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usercarddetails",
            name="online_card_created",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="usercarddetails",
            name="online_card_cvv",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="usercarddetails",
            name="online_card_expiry",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="usercarddetails",
            name="online_card_number",
            field=models.CharField(blank=True, max_length=19, null=True),
        ),
    ]
