# Generated by Django 5.1.7 on 2025-04-06 09:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercarddetails',
            name='strativa_card_expiry',
            field=models.DateField(default=datetime.datetime(2028, 4, 6, 9, 52, 51, 747920, tzinfo=datetime.timezone.utc)),
        ),
    ]
