# Generated by Django 5.1.7 on 2025-04-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdata",
            name="email",
            field=models.EmailField(
                default="csprojectserver@gmail.com", max_length=255
            ),
        ),
    ]
