# Generated by Django 5.1.7 on 2025-05-25 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccounts',
            name='account_number',
            field=models.TextField(unique=True),
        ),
    ]
