# Generated by Django 5.1.7 on 2025-04-17 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_accounts', '0003_alter_userdata_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='full_name',
            field=models.CharField(default='Test User Tu Testing', max_length=765),
        ),
    ]
