# Generated by Django 5.1.7 on 2025-04-17 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_accounts', '0004_userdata_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='full_name',
            field=models.CharField(max_length=765),
        ),
    ]
