# Generated by Django 5.1.7 on 2025-04-18 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_accounts", "0006_accounttypes_useraccounts"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercarddetails",
            name="account_number",
            field=models.CharField(
                default="CW-B40E4A704CD54883BCAF21DD15ED779D",
                max_length=50,
                unique=True,
            ),
        ),
    ]
