# Generated by Django 5.1.7 on 2025-04-18 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_accounts", "0008_accounttypes_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accounttypes",
            name="code",
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name="useraccounts",
            name="balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
