# Generated by Django 5.1.7 on 2025-04-19 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_accounts", "0009_alter_accounttypes_code_alter_useraccounts_balance"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usercarddetails",
            name="account_number",
        ),
        migrations.RemoveField(
            model_name="usercarddetails",
            name="balance",
        ),
        migrations.AlterField(
            model_name="useraccounts",
            name="account_number",
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
